=== ultraleap/driver_ultraleap/dev-resources/json/input_profile_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ultraleap/driver_ultraleap/dev-resources/json/input_profile_schema.json",

  "title": "SteamVR Input Profile",

  "$defs": {
    "resource_path": {
      "type": "string",
      "pattern": "^\\{.+\\}.+$"
    },
    "bindingui": {
      "type": "object",
      "properties": {
        "image": {"$ref": "#/$defs/resource_path"},
        "transform": {"type": "string"}
      }
    },
    "binding_image_point": {
      "type": "array",
      "items": {
        "type": "number",
        "minItems": 2,
        "maxItems": 2
      }
    }
  },

  "type": "object",
  "properties": {
    "jsonid": {"const": "input_profile"},
    "controller_type": {"type": "string"},
    "legacy_binding": {"$ref": "#/$defs/resource_path"},
    "remapping": {"$ref": "#/$defs/resource_path"},
    "input_bindingui_mode": {"enum": ["controller_handed", "hmd", "single_device"]},
    "input_bindingui_left": {"$ref": "#/$defs/bindingui"},
    "input_bindingui_right": {"$ref": "#/$defs/bindingui"},
    "input_source": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "/pose/.+": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"const": "pose"},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"}
          },
          "required": [
            "type",
            "binding_image_point"
          ]
        },
        "/input/pinch": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"const": "pinch"},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"},
            "order": {"type": "integer"},
            "value_source": {"type": "string", "pattern": "/input/.+"},
            "capsense_source": {"type": "string", "pattern": "/input/finger/.+"},
            "force_source": {"type": "string", "pattern": "/input/.+"}
          },
          "required": [
            "type",
            "binding_image_point"
          ]
        },
        "/input/finger/.+": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"const": "trigger"},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"},
            "order": {"type": "integer"},
            "click": {"type": "boolean"},
            "value": {"type": "boolean"},
            "touch": {"type": "boolean"},
            "force": {"type": "boolean"},
            "input_activity_path": {"type": "string"},
            "input_activity_threshold": {"type": "number"},
            "visibility": {"const": "InputValueVisibility_AvailableButHidden"}
          },
          "required": [
            "type",
            "binding_image_point"
          ]
        },
        "/input/skeleton/(left|right)": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"const": "skeleton"},
            "skeleton": {"enum": ["/skeleton/hand/left", "/skeleton/hand/right"]},
            "side": {"enum": ["left", "right"]},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"}
          },
          "required": [
            "type",
            "skeleton",
            "side",
            "binding_image_point"
          ]
        },
        "/input/.+": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"enum": ["joystick", "button", "trigger", "trackpad"]},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"},
            "order": {"type": "integer"},
            "click": {"type": "boolean"},
            "value": {"type": "boolean"},
            "touch": {"type": "boolean"},
            "force": {"type": "boolean"},
            "input_activity_path": {"type": "string"},
            "input_activity_threshold": {"type": "number"},
            "visibility": {
              "enum": [
                "InputValueVisibility_AvailableButHidden",
                "InputValueVisibility_None",
                "InputValueVisibility_Public",
                "InputValueVisibility_SteamVRInternal"
              ]
            }
          },
          "required": [
            "type",
            "binding_image_point"
          ]
        },
        "/output/.+": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {"const": "vibration"},
            "binding_image_point": {"$ref": "#/$defs/binding_image_point"}
          },
          "required": [
            "type",
            "binding_image_point"
          ]
        }
      },
      "required": [
        "/pose/raw"
      ]
    },
    "mirror_mappings": {
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": "string",
        "minItems": 2,
        "maxItems": 2
      }
    },
    "simulation_settings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "hmd_profile": {"type": "string"},
        "left_modelnumber": {"type": "string"},
        "right_modelnumber": {"type": "string"},
        "left_serialnumber": {"type": "string"},
        "right_serialnumber": {"type": "string"},
        "left_rendermodel": {"$ref": "#/$defs/resource_path"},
        "right_rendermodel": {"$ref": "#/$defs/resource_path"},
        "left_registered_device_type": {"type": "string"},
        "right_registered_device_type": {"type": "string"},
        "tracking_system_name": {"type": "string"},
        "manufacturer_name": {"type": "string"},
        "legacy_buttons": {"type": "array", "items": {"type": "number"}},
        "legacy_axis": {"type": "array", "items": {"type": "number"}}
      }
    },
    "default_bindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "app_key": {"type": "string"},
          "binding_url": {"type": "string"}
        }
      }
    }
  },
  "required": [
    "jsonid",
    "controller_type",
    "input_source"
  ]
}

=== ultraleap/driver_ultraleap/ultraleap/resources/input/ultraleap_hand_extended_profile.json
{
  "jsonid": "input_profile",
  "controller_type": "ultraleap_hand_extended",
  "legacy_binding": "{ultraleap}/input/legacy_binding_ultraleap_hand.json",
  "remapping": "{ultraleap}/input/ultraleap_hand_extended_remapping.json",
  "input_bindingui_mode": "controller_handed",
  "input_bindingui_left": {
    "transform": "scale(-1,1)",
    "image": "{ultraleap}/bindingui/ultraleap_hand.svg"
  },
  "input_bindingui_right": {
    "image": "{ultraleap}/bindingui/ultraleap_hand.svg"
  },
  "input_source": {
    "/input/pinch": {
      "type": "trigger",
      "binding_image_point": [96, 32],
      "value": true,
      "order": 1
    },

    "/input/grip": {
      "type": "trigger",
      "binding_image_point": [65, 105],
      "value": true,
      "order": 2
    },

    "/input/system" : {
      "type" : "button",
      "click" : true,
      "touch" : true,
      "binding_image_point" : [ 0,0 ],
      "order" : 1
    },
    "/input/a" : {
      "type" : "button",
      "click" : true,
      "touch" : true,
      "binding_image_point" : [ 0, 0 ],
      "order" : 6
    },
    "/input/b" : {
      "type" : "button",
      "click" : true,
      "touch" : true,
      "binding_image_point" : [ 0, 0  ],
      "order" : 5
    },
    "/input/trigger" : {
      "type" : "trigger",
      "click" : true,
      "touch" : true,
      "value" : true,
      "binding_image_point" : [ 0, 0 ],
      "order" : 2
    },
    "/input/trackpad" : {
      "type" : "trackpad",
      "force" : true,
      "touch" : true,
      "binding_image_point" : [ 0, 0 ],
      "order" : 3
    },
    "/input/thumbstick" : {
      "type" : "joystick",
      "click" : true,
      "touch" : true,
      "binding_image_point" : [ 0, 0 ],
      "order" : 4
    },


    "/pose/raw": {
      "type": "pose",
      "binding_image_point": [65, 105]
    },
    "/pose/handgrip": {
      "type": "pose",
      "binding_image_point": [65, 105]
    },
    "/pose/tip": {
      "type": "pose",
      "binding_image_point": [0, 0]
    },

    "/input/skeleton/left": {
      "type": "skeleton",
      "skeleton": "/skeleton/hand/left",
      "side": "left",
      "binding_image_point": [65, 105]
    },
    "/input/skeleton/right": {
      "type": "skeleton",
      "skeleton": "/skeleton/hand/right",
      "side": "right",
      "binding_image_point": [65, 105]
    },

    "/input/finger/thumb": {
      "type": "trigger",
      "visibility" : "InputValueVisibility_AvailableButHidden",
      "binding_image_point": [96, 32],
      "value": true,
      "order": 100
    },
    "/input/finger/index": {
      "type": "trigger",
      "visibility" : "InputValueVisibility_AvailableButHidden",
      "binding_image_point": [55, 8],
      "value": true,
      "order": 101
    },
    "/input/finger/middle": {
      "type": "trigger",
      "visibility" : "InputValueVisibility_AvailableButHidden",
      "binding_image_point": [35, 9],
      "value": true,
      "order": 102
    },
    "/input/finger/ring": {
      "type": "trigger",
      "visibility" : "InputValueVisibility_AvailableButHidden",
      "binding_image_point": [12, 21],
      "value": true,
      "order": 103
    },
    "/input/finger/pinky": {
      "type": "trigger",
      "visibility" : "InputValueVisibility_AvailableButHidden",
      "binding_image_point": [9, 48],
      "value": true,
      "order": 104
    }
  }
}
